Repository checkmo2025/BE, pull requests merged in 2025-08, with the labels that each got.

#50 Feat/49/calendar
  src/main/java/checkmo/domain/club/converter/ClubConverter.java
  src/main/java/checkmo/domain/club/facade/ClubQueryFacade.java
  src/main/java/checkmo/domain/club/facade/ClubQueryFacadeImpl.java
  src/main/java/checkmo/domain/club/repository/meeting/MeetingRepository.java
  src/main/java/checkmo/domain/club/service/query/ClubMeetingQueryService.java
  src/main/java/checkmo/domain/club/service/query/ClubMeetingQueryServiceImpl.java
  src/main/java/checkmo/domain/club/web/controller/ClubBookshelfController.java
  src/main/java/checkmo/domain/club/web/controller/ClubMeetingController.java
  src/main/java/checkmo/domain/club/web/dto/meeting/MeetingResponseDTO.java
  src/main/java/checkmo/domain/member/web/controller/MemberController.java
Labels: ✨ feature

#57 Feat/56/member follow
  .github/workflows/release.yml
  compose.yml
  scripts/codedeploy/after_install.sh
  scripts/codedeploy/stop.sh
  src/main/java/checkmo/HealthCheckController.java
  src/main/java/checkmo/apiPayload/code/status/ErrorStatus.java
  src/main/java/checkmo/domain/member/converter/MemberConverter.java
  src/main/java/checkmo/domain/member/entity/Follow.java
  src/main/java/checkmo/domain/member/facade/MemberCommandFacade.java
  src/main/java/checkmo/domain/member/facade/MemberCommandFacadeImpl.java
  src/main/java/checkmo/domain/member/facade/MemberQueryFacade.java
  src/main/java/checkmo/domain/member/facade/MemberQueryFacadeImpl.java
  src/main/java/checkmo/domain/member/repository/FollowRepository.java
  src/main/java/checkmo/domain/member/repository/MemberRepository.java
  src/main/java/checkmo/domain/member/service/command/MemberFollowCommandService.java
  src/main/java/checkmo/domain/member/service/command/MemberFollowCommandServiceImpl.java
  src/main/java/checkmo/domain/member/service/query/MemberFollowQueryService.java
  src/main/java/checkmo/domain/member/service/query/MemberFollowQueryServiceImpl.java
  src/main/java/checkmo/domain/member/service/query/MemberQueryService.java
  src/main/java/checkmo/domain/member/service/query/MemberQueryServiceImpl.java
  src/main/java/checkmo/domain/member/web/controller/MemberController.java
  src/main/java/checkmo/domain/member/web/dto/MemberResponseDTO.java
  src/main/java/checkmo/domain/notification/entity/Notification.java
  src/main/java/checkmo/domain/notification/service/command/NotificationCommandServiceImpl.java
  src/main/java/checkmo/event/FollowEvent.java
  src/main/resources/application-redis.yml
Labels: ✨ feature

#59 Feat/51/meeting info read
  src/main/java/checkmo/apiPayload/code/status/ErrorStatus.java
  src/main/java/checkmo/domain/club/converter/ClubConverter.java
  src/main/java/checkmo/domain/club/facade/ClubQueryFacade.java
  src/main/java/checkmo/domain/club/facade/ClubQueryFacadeImpl.java
  src/main/java/checkmo/domain/club/repository/meeting/BookReviewRepositoryCustomImpl.java
  src/main/java/checkmo/domain/club/repository/meeting/MeetingRepositoryCustom.java
  src/main/java/checkmo/domain/club/repository/meeting/MeetingRepositoryCustomImpl.java
  src/main/java/checkmo/domain/club/repository/meeting/TopicRepositoryCustomImpl.java
  src/main/java/checkmo/domain/club/service/query/ClubMeetingQueryService.java
  src/main/java/checkmo/domain/club/service/query/ClubMeetingQueryServiceImpl.java
  src/main/java/checkmo/domain/club/validation/validCursor/CursorValidator.java
  src/main/java/checkmo/domain/club/validation/validCursor/ValidCursor.java
  src/main/java/checkmo/domain/club/validation/validRate/RateValidator.java
  src/main/java/checkmo/domain/club/validation/validRate/ValidRate.java
  src/main/java/checkmo/domain/club/validation/validSize/SizeValidator.java
  src/main/java/checkmo/domain/club/validation/validSize/ValidSize.java
  src/main/java/checkmo/domain/club/web/controller/ClubBookshelfController.java
  src/main/java/checkmo/domain/club/web/controller/ClubMeetingController.java
  src/main/java/checkmo/domain/club/web/dto/bookshelf/BookShelfRequestDTO.java
  src/main/java/checkmo/domain/club/web/dto/meeting/MeetingResponseDTO.java
  src/main/java/checkmo/domain/member/facade/MemberQueryFacade.java
  src/main/java/checkmo/domain/member/facade/MemberQueryFacadeImpl.java
  src/main/java/checkmo/domain/member/service/query/MemberQueryService.java
  src/main/java/checkmo/domain/member/service/query/MemberQueryServiceImpl.java
Labels: ✨ feature, ♻️ refactor

#61 Feat/60/kakao login
  src/main/java/checkmo/config/SecurityConfig.java
  src/main/java/checkmo/domain/member/web/controller/AuthController.java
  src/main/resources/application-oauth2.yml
Labels: ✨ feature

#75 ✨ [Feat] Presigned Url 발급 API 구현
  build.gradle
  compose.yml
  nginx/conf.d/websites/checkmo.shop.conf
  src/main/java/checkmo/CheckmoApplication.java
  src/main/java/checkmo/apiPayload/code/status/ErrorStatus.java
  src/main/java/checkmo/config/S3Config.java
  src/main/java/checkmo/config/properties/S3Properties.java
  src/main/java/checkmo/domain/member/service/command/MemberProfileCommandServiceImpl.java
  src/main/java/checkmo/domain/member/web/controller/MemberController.java
  src/main/java/checkmo/domain/member/web/dto/MemberResponseDTO.java
  src/main/java/checkmo/global/s3/converter/S3Converter.java
  src/main/java/checkmo/global/s3/service/S3Service.java
  src/main/java/checkmo/global/s3/web/controller/S3Controller.java
  src/main/java/checkmo/global/s3/web/dto/S3RequestDTO.java
  src/main/java/checkmo/global/s3/web/dto/S3ResponseDTO.java
  src/main/resources/application-s3.yml
  src/main/resources/application.yml
Labels: ✨ feature

#80 ✨ [Feat] 독서 클럽 가입시 알림 생성 기능 개발
  src/main/java/checkmo/domain/club/service/command/ClubMembershipCommandServiceImpl.java
  src/main/java/checkmo/domain/notification/converter/NotificationConverter.java
  src/main/java/checkmo/domain/notification/entity/Notification.java
  src/main/java/checkmo/domain/notification/handler/NotificationEventHandler.java
  src/main/java/checkmo/domain/notification/service/command/NotificationCommandService.java
  src/main/java/checkmo/domain/notification/service/command/NotificationCommandServiceImpl.java
  src/main/java/checkmo/event/JoinClubEvent.java
  src/main/java/checkmo/global/dto/NotificationSharedDTO.java
Labels: ✨ feature

#86 ♻️[Refactor] API 응답 코드 추가
  src/main/java/checkmo/apiPayload/code/status/ErrorStatus.java
  src/main/java/checkmo/domain/member/web/controller/AuthController.java
  src/main/java/checkmo/domain/member/web/controller/MemberController.java
Labels: ♻️ refactor

#87 ✨ [FEAT] 독서모임 상세조회 기능
  src/main/java/checkmo/domain/club/converter/ClubConverter.java
  src/main/java/checkmo/domain/club/facade/ClubQueryFacade.java
  src/main/java/checkmo/domain/club/facade/ClubQueryFacadeImpl.java
  src/main/java/checkmo/domain/club/repository/ClubMemberRepository.java
  src/main/java/checkmo/domain/club/repository/announcement/NoticeRepository.java
  src/main/java/checkmo/domain/club/repository/meeting/MeetingRepository.java
  src/main/java/checkmo/domain/club/repository/meeting/MeetingRepositoryCustom.java
  src/main/java/checkmo/domain/club/repository/meeting/MeetingRepositoryCustomImpl.java
  src/main/java/checkmo/domain/club/repository/meeting/TeamRepository.java
  src/main/java/checkmo/domain/club/repository/meeting/TeamTopicRepository.java
  src/main/java/checkmo/domain/club/repository/meeting/TopicRepository.java
  src/main/java/checkmo/domain/club/repository/meeting/TopicRepositoryCustom.java
  src/main/java/checkmo/domain/club/repository/meeting/TopicRepositoryCustomImpl.java
  src/main/java/checkmo/domain/club/service/query/ClubCommunicationQueryServiceImpl.java
  src/main/java/checkmo/domain/club/service/query/ClubMeetingQueryService.java
  src/main/java/checkmo/domain/club/service/query/ClubMeetingQueryServiceImpl.java
  src/main/java/checkmo/domain/club/service/query/ClubQueryServiceImpl.java
  src/main/java/checkmo/domain/club/web/controller/ClubMeetingController.java
Labels: ✨ feature

#82 ✨ [FEAT] 미팅 팀 PUT
  src/main/java/checkmo/apiPayload/code/status/ErrorStatus.java
  src/main/java/checkmo/domain/club/entity/ClubMember.java
  src/main/java/checkmo/domain/club/entity/meeting/Meeting.java
  src/main/java/checkmo/domain/club/entity/meeting/MemberTeam.java
  src/main/java/checkmo/domain/club/entity/meeting/Team.java
  src/main/java/checkmo/domain/club/facade/ClubCommandFacade.java
  src/main/java/checkmo/domain/club/facade/ClubCommandFacadeImpl.java
  src/main/java/checkmo/domain/club/repository/ClubMemberRepository.java
  src/main/java/checkmo/domain/club/service/command/ClubMeetingCommandService.java
  src/main/java/checkmo/domain/club/service/command/ClubMeetingCommandServiceImpl.java
  src/main/java/checkmo/domain/club/service/query/ClubMemberQueryService.java
  src/main/java/checkmo/domain/club/service/query/ClubMemberQueryServiceImpl.java
  src/main/java/checkmo/domain/club/web/controller/ClubMeetingController.java
  src/main/java/checkmo/domain/club/web/dto/meeting/MeetingRequestDTO.java
  src/main/java/checkmo/domain/member/facade/MemberQueryFacade.java
  src/main/java/checkmo/domain/member/facade/MemberQueryFacadeImpl.java
  src/main/java/checkmo/domain/member/repository/MemberRepository.java
  src/main/java/checkmo/domain/member/service/query/MemberQueryService.java
  src/main/java/checkmo/domain/member/service/query/MemberQueryServiceImpl.java
Labels: ✨ feature

#96 ✨[Feat] 마이페이지 - 내가 가입한 클럽 조회
  src/main/java/checkmo/domain/club/converter/ClubConverter.java
  src/main/java/checkmo/domain/club/facade/ClubQueryFacade.java
  src/main/java/checkmo/domain/club/facade/ClubQueryFacadeImpl.java
  src/main/java/checkmo/domain/club/repository/ClubMemberRepository.java
  src/main/java/checkmo/domain/club/service/query/ClubMemberQueryService.java
  src/main/java/checkmo/domain/club/service/query/ClubMemberQueryServiceImpl.java
  src/main/java/checkmo/domain/club/web/controller/ClubController.java
  src/main/java/checkmo/domain/club/web/dto/club/ClubResponseDTO.java
Labels: ✨ feature

#92 ✨ [FEAT] 모임 공지사항 상세조회 API
  src/main/java/checkmo/apiPayload/code/status/ErrorStatus.java
  src/main/java/checkmo/domain/club/entity/announcement/Notice.java
  src/main/java/checkmo/domain/club/repository/announcement/NoticeRepository.java
  src/main/java/checkmo/domain/club/repository/announcement/VoteRepository.java
  src/main/java/checkmo/domain/club/service/command/ClubCommunicationCommandServiceImpl.java
  src/main/java/checkmo/domain/club/service/query/ClubCommunicationQueryServiceImpl.java
  src/main/java/checkmo/domain/club/web/controller/ClubNoticeController.java
Labels: ✨ feature, ♻️ refactor

#89 ✨ [FEAT] 미팅 전체 참석자/팀별 참석자 전체 조회
  src/main/java/checkmo/domain/club/converter/ClubConverter.java
  src/main/java/checkmo/domain/club/facade/ClubQueryFacade.java
  src/main/java/checkmo/domain/club/facade/ClubQueryFacadeImpl.java
  src/main/java/checkmo/domain/club/repository/ClubMemberRepository.java
  src/main/java/checkmo/domain/club/repository/ClubMemberRepositoryCustom.java
  src/main/java/checkmo/domain/club/repository/ClubMemberRepositoryCustomImpl.java
  src/main/java/checkmo/domain/club/repository/meeting/MemberTeamRepository.java
  src/main/java/checkmo/domain/club/service/query/ClubMeetingQueryService.java
  src/main/java/checkmo/domain/club/service/query/ClubMeetingQueryServiceImpl.java
  src/main/java/checkmo/domain/club/service/query/ClubMemberQueryService.java
  src/main/java/checkmo/domain/club/service/query/ClubMemberQueryServiceImpl.java
  src/main/java/checkmo/domain/club/service/query/ClubQueryService.java
  src/main/java/checkmo/domain/club/service/query/ClubQueryServiceImpl.java
  src/main/java/checkmo/domain/club/web/controller/ClubController.java
  src/main/java/checkmo/domain/club/web/controller/ClubMeetingController.java
  src/main/java/checkmo/domain/club/web/dto/bookshelf/BookShelfRequestDTO.java
  src/main/java/checkmo/domain/club/web/dto/meeting/MeetingResponseDTO.java
Labels: ✨ feature

#102 ♻️ [Refactor] 투표 응답에 시작/종료 시간 추가
  src/main/java/checkmo/domain/club/converter/ClubConverter.java
  src/main/java/checkmo/domain/club/web/dto/club/ClubResponseDTO.java
Labels: ♻️ refactor

#112 ♻️ refactor: 독서 클럽 검색 조건 추가 (name)
  src/main/java/checkmo/domain/club/facade/ClubQueryFacade.java
  src/main/java/checkmo/domain/club/facade/ClubQueryFacadeImpl.java
  src/main/java/checkmo/domain/club/repository/ClubRepositoryCustom.java
  src/main/java/checkmo/domain/club/repository/ClubRepositoryCustomImpl.java
  src/main/java/checkmo/domain/club/service/query/ClubQueryService.java
  src/main/java/checkmo/domain/club/service/query/ClubQueryServiceImpl.java
  src/main/java/checkmo/domain/club/web/controller/ClubController.java
Labels: ♻️ refactor

#114 [BUG] 미팅 Request DTO 검증 어노테이션 추가
  src/main/java/checkmo/domain/club/entity/announcement/Notice.java
  src/main/java/checkmo/domain/club/entity/meeting/Meeting.java
  src/main/java/checkmo/domain/club/web/dto/meeting/MeetingRequestDTO.java
Labels: 🐛 bug
